### ISSUE TITLE
Missing import in 0.2.2

### ISSUE THREAD

**Issue by tibue99** [shahriyardx/easy-pil#26]
After the recent update to 0.2.2, `memoization` was removed as a requirement. However, it is still used in the code. When using the new version, the following error occurs:
```
Traceback (most recent call last):
  File "C:\Users\Timo\Desktop\pythonProject\main.py", line 1, in <module>
    import easy_pil
  File "C:\Users\Timo\Desktop\pythonProject\venv\lib\site-packages\easy_pil\__init__.py", line 3, in <module>
    from .editor import Editor
  File "C:\Users\Timo\Desktop\pythonProject\venv\lib\site-packages\easy_pil\editor.py", line 10, in <module>
    from .font import Font
  File "C:\Users\Timo\Desktop\pythonProject\venv\lib\site-packages\easy_pil\font.py", line 3, in <module>
    from memoization import cached
ModuleNotFoundError: No module named 'memoization'
```

**Comment by shahriyardx** [comment]
0.2.2 uses @aiocache.cached(), you might be checking wrong version? 
![image](https://user-images.githubusercontent.com/40076722/236777769-8aa924c2-5af3-443b-b554-78315d1df9b4.png)
